#!/usr/bin/env bash
# configure ubuntu machine to instal Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!\\n Tame look at this " | sudo tee /var/www/html/index.html
sudo service nginx start
