#!/usr/bin/env bash
# script that transfers file from client to server securely using scp

#!/usr/bin/env bash
if [ "$#" -lt 3 ]; then
    echo "you are not entering correct arguments, please use 4 arguments"
else
    scp -i "$4"  "$1" "$3@$2":~/
fi
