#!/usr/bin/env bash
# Taks 1. Install your load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y
echo "
frontend 1270_main
         bind *:80
         mode http
         default_backend 1270_web_servers
backend 1270_web_servers
        balance roundrobin
        option forwardfor
        server 214703-web-01 54.175.223.8
        server 214703-web-02 35.175.104.36" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
