#!/usr/bin/env bash
# lets go to infinity and beyond and add I am invincible
#trap '"echo I am invincible!!!"' 15
while :
do 
      echo 'To infinity and beyond'
	 sleep 2
	 trap 'echo I am invincible!!!' 15
done
