#!/usr/bin/env bash
#Script that displays numbers 1 to 100 and fizz buzz in the middle
for i in range {1..100}
do
	if [ $((i % 15)) == 0 ]
	then
		echo 'FizzBuzz'
	elif [ $(( i % 3)) == 0 ]
	then
		echo 'FIZZ'
	elif [ $((i % 5)) == 0 ]
	then
		echo 'BUZZ'
	else
		echo $i
	fi
	(( i++ ))
done
