#!/usr/bin/env bash
# This script is displaying "Best School Hi" 10 times using while and if
i=0
while [ "$i" -ne 10 ]
do
	echo 'Best School'
	if [[ "$i" == 8 ]];
	then
	echo 'Hi'
	fi
	(( i++ ))
done
