#!/usr/bin/env bash
# This script loops from 1 to 10 using While if  elif else
n=0
while [ $n -le 9 ]
do
	if [[ "$n" -eq 3 ]]
	then
		echo 'bad luck'
	elif [[ "$n" -eq 7 ]]
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	(( n++ ))
done
