#!/usr/bin/env bash
# This script displays hours 0-12 and minutes 0-60
hour=0
min=1
while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	while [ "$min" -le 59 ]
		do
		echo $min
		(( min++ ))
	done
	min=1
	(( hour++ ))
done
