#!/usr/bin/env bash
#this script checks whether the file is exist or not and if exist
#checks whether the file is empty or not. also checks whether the 
#file is regular file or not
FILE=school
if [ -e "$FILE" ]
then 
	echo "school file exists"
	if [ -s "$FILE" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi
	else
		echo 'school file does not exist'
	fi
