#!/usr/bin/env bash
#this script resolves ip address to domain
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed '$ a 8.8.8.8\tfacebook.com' -i ~/hosts.new
cp -f ~/hosts.new /etc/hosts 
